name: 'Create Recommended Branch'
description: 'Creates a new branch with a recommended suffix based on the input branch name'
author: 'daffahilmyf'
inputs:
  branch_name:
    description: 'The name of the branch to base the new branch on'
    required: true
  token:
    description: 'GitHub token for authentication'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'blue'
  icon: 'git-branch'
